# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e5f013c97b411378597c5872427e60587524e351a3db27038c9a286a7d2f54c85466c93973bd815c3ea2919ef0c5edf2a8eae48a788997a21a1e94d2ae51f3

test:
  secret_key_base: 3f75de018af77a7e9c6e031cae9f67c895fb9d4074ecc9d29dce4282447b8ca80e9a867f9fbc87a7514ce6895e083a9d525a4cb1124bab766dac39c86d30b389

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
